<a href="https://colab.research.google.com/github/Zuleika28/ai2023zuleika/blob/main/Leccion1_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print("NumPy version:", np.__version__)


NumPy version: 1.23.5


In [ ]:
array_1d = np.arange(10)
print(array_1d)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
#crea
random_vector = np.random.rand(10)
#Encuentra indice
max_index = np.argmax(random_vector)
#remplaza
random_vector[max_index] = 0
#imprime
print("Vector original:")
print(random_vector)

Vector original:
[0.1975743  0.36382052 0.28830126 0.56920481 0.36877508 0.48720347
 0.         0.07097495 0.75478667 0.37319886]


In [ ]:
import numpy as np
# define
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
#imprime
print("Número 8 del array:", arr[1, 2])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

 # crea el array multidimensional
arr_2d = arr.reshape(7, 1)

print("Números [3, 4, 5] del array:")
print(arr_2d[2:5, 0])

Números [3, 4, 5] del array:
[3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print("Últimos 4 números del array:")
print(arr[-4:])

Últimos 4 números del array:
[4 5 6 7]


In [ ]:
import numpy as np

true_matrix = np.ones((3, 3), dtype=bool)

print("Matriz de 3x3 con todos los valores como True:")
print(true_matrix)

Matriz de 3x3 con todos los valores como True:
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
import numpy as np
#Numeros impares
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_numbers = arr[arr % 2 != 0]

print("Números impares del array:", odd_numbers)

Números impares del array: [1 3 5 7 9]


In [ ]:
import numpy as np

# Vector
vector = np.arange(10, 50)

print("Vector con valores desde 10 hasta 49:")
print(vector)

Vector con valores desde 10 hasta 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
import numpy as np

# Definir el vector
vector = np.array([1, 2, 3, 4, 5])

# Revertir el vector
vector_reversed = np.flip(vector)

# Imprimir el vector revertido
print("Vector revertido:", vector_reversed)

Vector revertido: [5 4 3 2 1]


In [ ]:
import numpy as np

random_matrix = np.random.randint(0, 100, size=(10, 10))

min_value = np.min(random_matrix)
max_value = np.max(random_matrix)

print("Matriz de 10x10 con valores enteros aleatorios:")
print(random_matrix)
print("Valor mínimo en la matriz:", min_value)

print("Valor máximo en la matriz:", max_value)

Matriz de 10x10 con valores enteros aleatorios:
[[28 80 90  3 38 70 52 96 20 81]
 [70 96 91 73  1  4  5 30 49 19]
 [82 54 59 87 86 37 84 90 24 15]
 [57 62 11 34 91 91 26 79 56 36]
 [89 78  0 74 95 55 89 48 24 70]
 [21 69 90 87 29  5  4 51 77  8]
 [63 47 41 86 73 12 27 69 82 92]
 [90 47 99 14 88 55 18 15 34 98]
 [10 85 93 18 90 24 96 77 76 35]
 [96  9 18 66 38 96 91 67 66  1]]
Valor mínimo en la matriz: 0
Valor máximo en la matriz: 99


In [ ]:
import numpy as np
#tridimencional
random_array = np.random.rand(3, 3, 3)

print("Array tridimensional de 3x3x3 con valores aleatorios:")
print(random_array)

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reemplaza impares
arr[arr % 2 != 0] = -1

print("Array con números impares reemplazados por -1:")
print(arr)

Array con números impares reemplazados por -1:
[-1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
import numpy as np

# Crear un array de tipo float
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5])

# Imprimir el array
print("Array de tipo float:")
print(float_array)

Array de tipo float:
[1.1 2.2 3.3 4.4 5.5]


In [ ]:
import numpy as np

#  unidimensional
array_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Convertir unidimensional a bidimensional
array_2d = array_1d.reshape(2, -1)

print("Array bidimensional con 2 filas:")
print(array_2d)

Array bidimensional con 2 filas:
[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

resultado = np.vstack((a, b))

print("verticalmente:")
print(resultado)

verticalmente:
[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

resultado = np.hstack((a, b))

print("horizontalmente:")
print(resultado)

horizontalmente:
[1 2 3 4 5 6]


In [ ]:
import numpy as np

tmp = np.arange(15)
result = tmp[5:11]

print(result)

[ 5  6  7  8  9 10]


In [ ]:
# Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# pair_max(a, b)
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])


# your code here
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [ ]:
# Swap columns 1 and 2 in the array arr.
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]


arr = np.arange(9).reshape(3,3)
print(arr)
# your code here
pass

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np

# Establecer la semilla para reproducibilidad
np.random.seed(42)

# Crear una matriz de 5x3 con números decimales aleatorios entre 5 y 10
matriz_aleatoria = np.random.uniform(5, 10, size=(5, 3))
print(matriz_aleatoria)

[[6.87270059 9.75357153 8.65996971]
 [7.99329242 5.7800932  5.7799726 ]
 [5.29041806 9.33088073 8.00557506]
 [8.54036289 5.10292247 9.84954926]
 [9.1622132  6.06169555 5.90912484]]
