<a href="https://colab.research.google.com/github/Zuleika28/ai2023zuleika/blob/main/Numpy_IA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy.core.multiarray import zeros
import numpy as np

aux=np.array([1,2,4,5])
print(aux)
print(aux.shape)


aux=np.array([[1,2,3,4],[1,2,3,4]])
print(aux.shape)
print(aux)
print(type(aux))


tmp=np.zeros([4,4])
print(tmp)


tmp=np.full([4,4],5)
print(tmp)


tmp=np.eye(4,4)
print(tmp)

print("-------------------------")
tmp=np.ones([4,4])
print(tmp)

print(tmp.shape)

[1 2 4 5]
(4,)
(2, 4)
[[1 2 3 4]
 [1 2 3 4]]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
-------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
(4, 4)


In [ ]:
tmp=10*np.random.random([3,3])
print(tmp)

[[1.36529812 6.45954779 0.04573917]
 [4.51191804 1.1309072  5.13337449]
 [7.58343265 8.55258021 5.66248526]]


In [ ]:
print(tmp[:2,:2])

[[1.36529812 6.45954779]
 [4.51191804 1.1309072 ]]


In [ ]:
print(tmp[:2,1:3])

[[6.45954779 0.04573917]
 [1.1309072  5.13337449]]


In [ ]:
print(tmp[2,2])

5.662485255730959


In [ ]:
tmp=10*np.random.random([3,3])
print(tmp)

[[9.11479225 5.37197602 9.68708941]
 [2.04107105 2.64210816 3.38468731]
 [9.59707068 4.35109833 7.42206611]]


In [ ]:
mask=tmp>5
print(tmp[mask])

[9.11479225 5.37197602 9.68708941 9.59707068 7.42206611]


In [ ]:
mask=(tmp>=2) & (tmp<=4)
print(tmp[mask])

[2.04107105 2.64210816 3.38468731]


In [ ]:
np = np.random.randint(0,100, (4,4))

np = np[np % 2 == 0]
print(np)

[[74 89 87 80]
 [33 25 82 31]
 [29 94 95 59]
 [53 54 58 98]]
[84 66 10 68 54 82 44 70 90 14 86 62]


In [ ]:
import numpy as np

# Create an array with integer values batween 1 and 10
a=np.random.randint(1,11,size=(3,4))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(a.shape)
print(b.shape)
print("adding numbers")
print(a+b)
print("substracting numbers")
print(a-b)

print(np.add(a,b))
print(np.multiply(a,b))

[[ 4  4  4  7]
 [ 6  1 10 10]
 [ 2  8  6  3]]
[[3 9 2 4]
 [3 6 9 4]
 [3 1 1 6]]
(3, 4)
(3, 4)
adding numbers
[[ 7 13  6 11]
 [ 9  7 19 14]
 [ 5  9  7  9]]
substracting numbers
[[ 1 -5  2  3]
 [ 3 -5  1  6]
 [-1  7  5 -3]]
[[ 7 13  6 11]
 [ 9  7 19 14]
 [ 5  9  7  9]]
[[12 36  8 28]
 [18  6 90 40]
 [ 6  8  6 18]]


In [ ]:
a=np.random.randint(1,11,size=(2,3))
b=np.random.randint(1,11,size=(3,4))
print(a)
print(b)
print(np.dot(a,b))
print(a.dot(b))

[[5 3 7]
 [3 4 8]]
[[ 9  6  1 10]
 [ 8  2  5  3]
 [10  4  4  3]]
[[139  64  48  80]
 [139  58  55  66]]
[[139  64  48  80]
 [139  58  55  66]]


In [ ]:
a=np.random.randint(1,11,size=(2,2))
print(a.shape)
print(type(a))
print(a)
print(a.T)

(2, 2)
<class 'numpy.ndarray'>
[[ 1  4]
 [10  1]]
[[ 1 10]
 [ 4  1]]


In [ ]:
a=np.random.randint(1,11,size=(4,3))
b=np.array([1,0,2])
print(a.shape)
print(b.shape)

c=np.empty_like(a)
print(a)
print(b)

print(c.shape)
print("----------------------")
print(c)

(4, 3)
(3,)
[[ 8  3  2]
 [ 6  5  3]
 [ 3  4  6]
 [ 2 10  6]]
[1 0 2]
(4, 3)
----------------------
[[ 4  4  4]
 [ 7  6  1]
 [10 10  2]
 [ 8  6  3]]


In [ ]:
for i in range(4):
  c[i,:]=a[i,:]+b

print (a)
print (b)
print (c)

c=a+b
print(c)

[[ 8  3  2]
 [ 6  5  3]
 [ 3  4  6]
 [ 2 10  6]]
[1 0 2]
[[ 9  3  4]
 [ 7  5  5]
 [ 4  4  8]
 [ 3 10  8]]
[[ 9  3  4]
 [ 7  5  5]
 [ 4  4  8]
 [ 3 10  8]]


In [ ]:
a=np.array([1,2,3])

print(a)

tmp=np.tile(a,(6,1))
print(tmp)

[1 2 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
a=np.random.randint(0,10,size=(6,6))
print(a)
aux=np.mean(a)
print(aux)



print(a.mean(axis=1))

[[8 3 7 2 6 1]
 [6 6 4 4 8 4]
 [8 6 9 9 2 5]
 [4 1 1 9 5 6]
 [8 5 7 5 0 5]
 [9 9 2 3 0 2]]
4.972222222222222
[4.5        5.33333333 6.5        4.33333333 5.         4.16666667]
